# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 90

# Number of days of inactivity before a stale Issue or Pull Request is closed
daysUntilClose: 14

# Issues or Pull Requests with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - enhancement
  - bug
  - "in progress"
  - "help wanted"
  - "lean-proofs"

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale
markComment: >
  This issue/PR has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within 14 days.
  Thank you for your contributions.

# Comment to post when closing a stale Issue or Pull Request
closeComment: >
  This issue/PR has been automatically closed due to inactivity.
  Please feel free to reopen if this is still relevant.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Set to true to ignore issues with an assignee
exemptAssignees: true
